// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: accompany.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accompany struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int32                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Era           int32                  `protobuf:"varint,2,opt,name=Era,proto3" json:"Era,omitempty"`
	Speaklanguage []string               `protobuf:"bytes,3,rep,name=Speaklanguage,proto3" json:"Speaklanguage,omitempty"`
	FindType      string                 `protobuf:"bytes,4,opt,name=FindType,proto3" json:"FindType,omitempty"`
	Sociability   string                 `protobuf:"bytes,5,opt,name=Sociability,proto3" json:"Sociability,omitempty"`
	InfoChangedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=InfoChangedAt,proto3" json:"InfoChangedAt,omitempty"`
}

func (x *Accompany) Reset() {
	*x = Accompany{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accompany_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Accompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accompany) ProtoMessage() {}

func (x *Accompany) ProtoReflect() protoreflect.Message {
	mi := &file_accompany_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accompany.ProtoReflect.Descriptor instead.
func (*Accompany) Descriptor() ([]byte, []int) {
	return file_accompany_proto_rawDescGZIP(), []int{0}
}

func (x *Accompany) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Accompany) GetEra() int32 {
	if x != nil {
		return x.Era
	}
	return 0
}

func (x *Accompany) GetSpeaklanguage() []string {
	if x != nil {
		return x.Speaklanguage
	}
	return nil
}

func (x *Accompany) GetFindType() string {
	if x != nil {
		return x.FindType
	}
	return ""
}

func (x *Accompany) GetSociability() string {
	if x != nil {
		return x.Sociability
	}
	return ""
}

func (x *Accompany) GetInfoChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InfoChangedAt
	}
	return nil
}

var File_accompany_proto protoreflect.FileDescriptor

var file_accompany_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x45, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x72, 0x61, 0x12, 0x24,
	0x0a, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x12, 0x40, 0x0a, 0x0d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x41, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accompany_proto_rawDescOnce sync.Once
	file_accompany_proto_rawDescData = file_accompany_proto_rawDesc
)

func file_accompany_proto_rawDescGZIP() []byte {
	file_accompany_proto_rawDescOnce.Do(func() {
		file_accompany_proto_rawDescData = protoimpl.X.CompressGZIP(file_accompany_proto_rawDescData)
	})
	return file_accompany_proto_rawDescData
}

var file_accompany_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_accompany_proto_goTypes = []interface{}{
	(*Accompany)(nil),             // 0: pb.Accompany
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_accompany_proto_depIdxs = []int32{
	1, // 0: pb.Accompany.InfoChangedAt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accompany_proto_init() }
func file_accompany_proto_init() {
	if File_accompany_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accompany_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Accompany); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accompany_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accompany_proto_goTypes,
		DependencyIndexes: file_accompany_proto_depIdxs,
		MessageInfos:      file_accompany_proto_msgTypes,
	}.Build()
	File_accompany_proto = out.File
	file_accompany_proto_rawDesc = nil
	file_accompany_proto_goTypes = nil
	file_accompany_proto_depIdxs = nil
}
