// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: lover.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lover struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int32                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MinAge        int32                  `protobuf:"varint,2,opt,name=MinAge,proto3" json:"MinAge,omitempty"`
	MaxAge        int32                  `protobuf:"varint,3,opt,name=MaxAge,proto3" json:"MaxAge,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Sexual        string                 `protobuf:"bytes,6,opt,name=Sexual,proto3" json:"Sexual,omitempty"`
	Speaklanguage string                 `protobuf:"bytes,7,opt,name=Speaklanguage,proto3" json:"Speaklanguage,omitempty"`
	InfoChangedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=InfoChangedAt,proto3" json:"InfoChangedAt,omitempty"`
}

func (x *Lover) Reset() {
	*x = Lover{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lover_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lover) ProtoMessage() {}

func (x *Lover) ProtoReflect() protoreflect.Message {
	mi := &file_lover_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lover.ProtoReflect.Descriptor instead.
func (*Lover) Descriptor() ([]byte, []int) {
	return file_lover_proto_rawDescGZIP(), []int{0}
}

func (x *Lover) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Lover) GetMinAge() int32 {
	if x != nil {
		return x.MinAge
	}
	return 0
}

func (x *Lover) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Lover) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Lover) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Lover) GetSexual() string {
	if x != nil {
		return x.Sexual
	}
	return ""
}

func (x *Lover) GetSpeaklanguage() string {
	if x != nil {
		return x.Speaklanguage
	}
	return ""
}

func (x *Lover) GetInfoChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InfoChangedAt
	}
	return nil
}

var File_lover_proto protoreflect.FileDescriptor

var file_lover_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xfb, 0x01, 0x0a, 0x05, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x69, 0x6e, 0x41, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4d, 0x69, 0x6e, 0x41, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x4d, 0x61, 0x78, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4d, 0x61,
	0x78, 0x41, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x78, 0x75, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x65, 0x78, 0x75, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x61,
	0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x40,
	0x0a, 0x0d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x41, 0x74,
	0x42, 0x0c, 0x5a, 0x0a, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lover_proto_rawDescOnce sync.Once
	file_lover_proto_rawDescData = file_lover_proto_rawDesc
)

func file_lover_proto_rawDescGZIP() []byte {
	file_lover_proto_rawDescOnce.Do(func() {
		file_lover_proto_rawDescData = protoimpl.X.CompressGZIP(file_lover_proto_rawDescData)
	})
	return file_lover_proto_rawDescData
}

var file_lover_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lover_proto_goTypes = []interface{}{
	(*Lover)(nil),                 // 0: pb.Lover
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_lover_proto_depIdxs = []int32{
	1, // 0: pb.Lover.InfoChangedAt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lover_proto_init() }
func file_lover_proto_init() {
	if File_lover_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lover_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lover); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lover_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lover_proto_goTypes,
		DependencyIndexes: file_lover_proto_depIdxs,
		MessageInfos:      file_lover_proto_msgTypes,
	}.Build()
	File_lover_proto = out.File
	file_lover_proto_rawDesc = nil
	file_lover_proto_goTypes = nil
	file_lover_proto_depIdxs = nil
}
