// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: rpc_chatRecord.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create
type CreateChatRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int32  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TargetID int32  `protobuf:"varint,2,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	MsgType  string `protobuf:"bytes,3,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	Message  string `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Images   string `protobuf:"bytes,5,opt,name=Images,proto3" json:"Images,omitempty"`
}

func (x *CreateChatRecordRequest) Reset() {
	*x = CreateChatRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chatRecord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRecordRequest) ProtoMessage() {}

func (x *CreateChatRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatRecord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRecordRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chatRecord_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRecordRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateChatRecordRequest) GetTargetID() int32 {
	if x != nil {
		return x.TargetID
	}
	return 0
}

func (x *CreateChatRecordRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *CreateChatRecordRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateChatRecordRequest) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

type CreateChatRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatRecord *ChatRecord `protobuf:"bytes,1,opt,name=ChatRecord,proto3" json:"ChatRecord,omitempty"`
}

func (x *CreateChatRecordResponse) Reset() {
	*x = CreateChatRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chatRecord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChatRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRecordResponse) ProtoMessage() {}

func (x *CreateChatRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatRecord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateChatRecordResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chatRecord_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatRecordResponse) GetChatRecord() *ChatRecord {
	if x != nil {
		return x.ChatRecord
	}
	return nil
}

// Get
type GetChatRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TargetID int32 `protobuf:"varint,2,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
}

func (x *GetChatRecordRequest) Reset() {
	*x = GetChatRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chatRecord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRecordRequest) ProtoMessage() {}

func (x *GetChatRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatRecord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRecordRequest.ProtoReflect.Descriptor instead.
func (*GetChatRecordRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chatRecord_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatRecordRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetChatRecordRequest) GetTargetID() int32 {
	if x != nil {
		return x.TargetID
	}
	return 0
}

type GetChatRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatRecord []*ChatRecord `protobuf:"bytes,1,rep,name=ChatRecord,proto3" json:"ChatRecord,omitempty"`
}

func (x *GetChatRecordResponse) Reset() {
	*x = GetChatRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chatRecord_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRecordResponse) ProtoMessage() {}

func (x *GetChatRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatRecord_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRecordResponse.ProtoReflect.Descriptor instead.
func (*GetChatRecordResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chatRecord_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatRecordResponse) GetChatRecord() []*ChatRecord {
	if x != nil {
		return x.ChatRecord
	}
	return nil
}

// Update
type UpdateChatRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int32                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TargetID int32                  `protobuf:"varint,2,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	MsgType  string                 `protobuf:"bytes,3,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	Message  string                 `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	CreateAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
}

func (x *UpdateChatRecordRequest) Reset() {
	*x = UpdateChatRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chatRecord_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChatRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRecordRequest) ProtoMessage() {}

func (x *UpdateChatRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatRecord_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRecordRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chatRecord_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateChatRecordRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateChatRecordRequest) GetTargetID() int32 {
	if x != nil {
		return x.TargetID
	}
	return 0
}

func (x *UpdateChatRecordRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *UpdateChatRecordRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateChatRecordRequest) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type UpdateChatRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatRecord *ChatRecord `protobuf:"bytes,1,opt,name=ChatRecord,proto3" json:"ChatRecord,omitempty"`
}

func (x *UpdateChatRecordResponse) Reset() {
	*x = UpdateChatRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chatRecord_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChatRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRecordResponse) ProtoMessage() {}

func (x *UpdateChatRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chatRecord_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatRecordResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chatRecord_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateChatRecordResponse) GetChatRecord() *ChatRecord {
	if x != nil {
		return x.ChatRecord
	}
	return nil
}

var File_rpc_chatRecord_proto protoreflect.FileDescriptor

var file_rpc_chatRecord_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x10, 0x63, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x18, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x4a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49,
	0x44, 0x22, 0x47, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0xb9, 0x01, 0x0a, 0x17, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36,
	0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x4a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_chatRecord_proto_rawDescOnce sync.Once
	file_rpc_chatRecord_proto_rawDescData = file_rpc_chatRecord_proto_rawDesc
)

func file_rpc_chatRecord_proto_rawDescGZIP() []byte {
	file_rpc_chatRecord_proto_rawDescOnce.Do(func() {
		file_rpc_chatRecord_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_chatRecord_proto_rawDescData)
	})
	return file_rpc_chatRecord_proto_rawDescData
}

var file_rpc_chatRecord_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_chatRecord_proto_goTypes = []interface{}{
	(*CreateChatRecordRequest)(nil),  // 0: pb.CreateChatRecordRequest
	(*CreateChatRecordResponse)(nil), // 1: pb.CreateChatRecordResponse
	(*GetChatRecordRequest)(nil),     // 2: pb.GetChatRecordRequest
	(*GetChatRecordResponse)(nil),    // 3: pb.GetChatRecordResponse
	(*UpdateChatRecordRequest)(nil),  // 4: pb.UpdateChatRecordRequest
	(*UpdateChatRecordResponse)(nil), // 5: pb.UpdateChatRecordResponse
	(*ChatRecord)(nil),               // 6: pb.ChatRecord
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_rpc_chatRecord_proto_depIdxs = []int32{
	6, // 0: pb.CreateChatRecordResponse.ChatRecord:type_name -> pb.ChatRecord
	6, // 1: pb.GetChatRecordResponse.ChatRecord:type_name -> pb.ChatRecord
	7, // 2: pb.UpdateChatRecordRequest.CreateAt:type_name -> google.protobuf.Timestamp
	6, // 3: pb.UpdateChatRecordResponse.ChatRecord:type_name -> pb.ChatRecord
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_chatRecord_proto_init() }
func file_rpc_chatRecord_proto_init() {
	if File_rpc_chatRecord_proto != nil {
		return
	}
	file_chatRecord_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_chatRecord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chatRecord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChatRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chatRecord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chatRecord_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chatRecord_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChatRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chatRecord_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChatRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_chatRecord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_chatRecord_proto_goTypes,
		DependencyIndexes: file_rpc_chatRecord_proto_depIdxs,
		MessageInfos:      file_rpc_chatRecord_proto_msgTypes,
	}.Build()
	File_rpc_chatRecord_proto = out.File
	file_rpc_chatRecord_proto_rawDesc = nil
	file_rpc_chatRecord_proto_goTypes = nil
	file_rpc_chatRecord_proto_depIdxs = nil
}
