// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: rpc_accompany.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccompanyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int32  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Era           int32  `protobuf:"varint,2,opt,name=Era,proto3" json:"Era,omitempty"`
	City          string `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	Gender        string `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Speaklanguage string `protobuf:"bytes,5,opt,name=Speaklanguage,proto3" json:"Speaklanguage,omitempty"`
	FindType      string `protobuf:"bytes,6,opt,name=FindType,proto3" json:"FindType,omitempty"`
	FindTarget    string `protobuf:"bytes,7,opt,name=FindTarget,proto3" json:"FindTarget,omitempty"`
	Sociability   string `protobuf:"bytes,8,opt,name=Sociability,proto3" json:"Sociability,omitempty"`
	Certification bool   `protobuf:"varint,9,opt,name=Certification,proto3" json:"Certification,omitempty"`
}

func (x *CreateAccompanyRequest) Reset() {
	*x = CreateAccompanyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accompany_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccompanyRequest) ProtoMessage() {}

func (x *CreateAccompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accompany_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateAccompanyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_accompany_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccompanyRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateAccompanyRequest) GetEra() int32 {
	if x != nil {
		return x.Era
	}
	return 0
}

func (x *CreateAccompanyRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAccompanyRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateAccompanyRequest) GetSpeaklanguage() string {
	if x != nil {
		return x.Speaklanguage
	}
	return ""
}

func (x *CreateAccompanyRequest) GetFindType() string {
	if x != nil {
		return x.FindType
	}
	return ""
}

func (x *CreateAccompanyRequest) GetFindTarget() string {
	if x != nil {
		return x.FindTarget
	}
	return ""
}

func (x *CreateAccompanyRequest) GetSociability() string {
	if x != nil {
		return x.Sociability
	}
	return ""
}

func (x *CreateAccompanyRequest) GetCertification() bool {
	if x != nil {
		return x.Certification
	}
	return false
}

type CreateAccompanyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ac *Accompany `protobuf:"bytes,1,opt,name=ac,proto3" json:"ac,omitempty"`
}

func (x *CreateAccompanyResponse) Reset() {
	*x = CreateAccompanyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accompany_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccompanyResponse) ProtoMessage() {}

func (x *CreateAccompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accompany_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccompanyResponse.ProtoReflect.Descriptor instead.
func (*CreateAccompanyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_accompany_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccompanyResponse) GetAc() *Accompany {
	if x != nil {
		return x.Ac
	}
	return nil
}

type GetAccompanyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *GetAccompanyRequest) Reset() {
	*x = GetAccompanyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accompany_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccompanyRequest) ProtoMessage() {}

func (x *GetAccompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accompany_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccompanyRequest.ProtoReflect.Descriptor instead.
func (*GetAccompanyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_accompany_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccompanyRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetAccompanyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ac *Accompany `protobuf:"bytes,1,opt,name=ac,proto3" json:"ac,omitempty"`
}

func (x *GetAccompanyResponse) Reset() {
	*x = GetAccompanyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accompany_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccompanyResponse) ProtoMessage() {}

func (x *GetAccompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accompany_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccompanyResponse.ProtoReflect.Descriptor instead.
func (*GetAccompanyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_accompany_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccompanyResponse) GetAc() *Accompany {
	if x != nil {
		return x.Ac
	}
	return nil
}

type UpdateAccompanyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int32  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Era           int32  `protobuf:"varint,2,opt,name=Era,proto3" json:"Era,omitempty"`
	City          string `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	Gender        string `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Speaklanguage string `protobuf:"bytes,5,opt,name=Speaklanguage,proto3" json:"Speaklanguage,omitempty"`
	FindType      string `protobuf:"bytes,6,opt,name=FindType,proto3" json:"FindType,omitempty"`
	FindTarget    string `protobuf:"bytes,7,opt,name=FindTarget,proto3" json:"FindTarget,omitempty"`
	Sociability   string `protobuf:"bytes,8,opt,name=Sociability,proto3" json:"Sociability,omitempty"`
	Certification bool   `protobuf:"varint,9,opt,name=Certification,proto3" json:"Certification,omitempty"`
}

func (x *UpdateAccompanyRequest) Reset() {
	*x = UpdateAccompanyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accompany_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccompanyRequest) ProtoMessage() {}

func (x *UpdateAccompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accompany_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccompanyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccompanyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_accompany_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAccompanyRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateAccompanyRequest) GetEra() int32 {
	if x != nil {
		return x.Era
	}
	return 0
}

func (x *UpdateAccompanyRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateAccompanyRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateAccompanyRequest) GetSpeaklanguage() string {
	if x != nil {
		return x.Speaklanguage
	}
	return ""
}

func (x *UpdateAccompanyRequest) GetFindType() string {
	if x != nil {
		return x.FindType
	}
	return ""
}

func (x *UpdateAccompanyRequest) GetFindTarget() string {
	if x != nil {
		return x.FindTarget
	}
	return ""
}

func (x *UpdateAccompanyRequest) GetSociability() string {
	if x != nil {
		return x.Sociability
	}
	return ""
}

func (x *UpdateAccompanyRequest) GetCertification() bool {
	if x != nil {
		return x.Certification
	}
	return false
}

type UpdateAccompanyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ac *Accompany `protobuf:"bytes,1,opt,name=ac,proto3" json:"ac,omitempty"`
}

func (x *UpdateAccompanyResponse) Reset() {
	*x = UpdateAccompanyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accompany_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccompanyResponse) ProtoMessage() {}

func (x *UpdateAccompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accompany_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccompanyResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccompanyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_accompany_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccompanyResponse) GetAc() *Accompany {
	if x != nil {
		return x.Ac
	}
	return nil
}

var File_rpc_accompany_proto protoreflect.FileDescriptor

var file_rpc_accompany_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x02, 0x0a, 0x16, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x45, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x72, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43,
	0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x53,
	0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12,
	0x24, 0x0a, 0x0d, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x38, 0x0a, 0x17, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x02, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x02, 0x61, 0x63, 0x22,
	0x2d, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x35,
	0x0a, 0x14, 0x67, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x52, 0x02, 0x61, 0x63, 0x22, 0x98, 0x02, 0x0a, 0x16, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x72, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53,
	0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x69,
	0x6e, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x38, 0x0a, 0x17, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x61,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x02, 0x61, 0x63, 0x42, 0x0c, 0x5a, 0x0a, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_accompany_proto_rawDescOnce sync.Once
	file_rpc_accompany_proto_rawDescData = file_rpc_accompany_proto_rawDesc
)

func file_rpc_accompany_proto_rawDescGZIP() []byte {
	file_rpc_accompany_proto_rawDescOnce.Do(func() {
		file_rpc_accompany_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_accompany_proto_rawDescData)
	})
	return file_rpc_accompany_proto_rawDescData
}

var file_rpc_accompany_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_accompany_proto_goTypes = []interface{}{
	(*CreateAccompanyRequest)(nil),  // 0: pb.createAccompanyRequest
	(*CreateAccompanyResponse)(nil), // 1: pb.createAccompanyResponse
	(*GetAccompanyRequest)(nil),     // 2: pb.getAccompanyRequest
	(*GetAccompanyResponse)(nil),    // 3: pb.getAccompanyResponse
	(*UpdateAccompanyRequest)(nil),  // 4: pb.updateAccompanyRequest
	(*UpdateAccompanyResponse)(nil), // 5: pb.updateAccompanyResponse
	(*Accompany)(nil),               // 6: pb.accompany
}
var file_rpc_accompany_proto_depIdxs = []int32{
	6, // 0: pb.createAccompanyResponse.ac:type_name -> pb.accompany
	6, // 1: pb.getAccompanyResponse.ac:type_name -> pb.accompany
	6, // 2: pb.updateAccompanyResponse.ac:type_name -> pb.accompany
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_accompany_proto_init() }
func file_rpc_accompany_proto_init() {
	if File_rpc_accompany_proto != nil {
		return
	}
	file_accompany_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_accompany_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccompanyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accompany_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccompanyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accompany_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccompanyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accompany_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccompanyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accompany_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccompanyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accompany_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccompanyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_accompany_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_accompany_proto_goTypes,
		DependencyIndexes: file_rpc_accompany_proto_depIdxs,
		MessageInfos:      file_rpc_accompany_proto_msgTypes,
	}.Build()
	File_rpc_accompany_proto = out.File
	file_rpc_accompany_proto_rawDesc = nil
	file_rpc_accompany_proto_goTypes = nil
	file_rpc_accompany_proto_depIdxs = nil
}
