// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: rpc_hobby.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int32  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Era           int32  `protobuf:"varint,2,opt,name=Era,proto3" json:"Era,omitempty"`
	City          string `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	Gender        string `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Height        int32  `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	Weight        int32  `protobuf:"varint,6,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Speaklanguage string `protobuf:"bytes,7,opt,name=Speaklanguage,proto3" json:"Speaklanguage,omitempty"`
	FindType      string `protobuf:"bytes,8,opt,name=FindType,proto3" json:"FindType,omitempty"`
	FindTarget    string `protobuf:"bytes,9,opt,name=FindTarget,proto3" json:"FindTarget,omitempty"`
	Experience    int32  `protobuf:"varint,10,opt,name=Experience,proto3" json:"Experience,omitempty"`
	Sociability   string `protobuf:"bytes,11,opt,name=Sociability,proto3" json:"Sociability,omitempty"`
	Certification bool   `protobuf:"varint,12,opt,name=Certification,proto3" json:"Certification,omitempty"`
}

func (x *CreateHobbyRequest) Reset() {
	*x = CreateHobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_hobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHobbyRequest) ProtoMessage() {}

func (x *CreateHobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_hobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateHobbyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_hobby_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHobbyRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateHobbyRequest) GetEra() int32 {
	if x != nil {
		return x.Era
	}
	return 0
}

func (x *CreateHobbyRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateHobbyRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateHobbyRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateHobbyRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateHobbyRequest) GetSpeaklanguage() string {
	if x != nil {
		return x.Speaklanguage
	}
	return ""
}

func (x *CreateHobbyRequest) GetFindType() string {
	if x != nil {
		return x.FindType
	}
	return ""
}

func (x *CreateHobbyRequest) GetFindTarget() string {
	if x != nil {
		return x.FindTarget
	}
	return ""
}

func (x *CreateHobbyRequest) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *CreateHobbyRequest) GetSociability() string {
	if x != nil {
		return x.Sociability
	}
	return ""
}

func (x *CreateHobbyRequest) GetCertification() bool {
	if x != nil {
		return x.Certification
	}
	return false
}

type CreateHobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H *Hobby `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *CreateHobbyResponse) Reset() {
	*x = CreateHobbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_hobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHobbyResponse) ProtoMessage() {}

func (x *CreateHobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_hobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateHobbyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_hobby_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHobbyResponse) GetH() *Hobby {
	if x != nil {
		return x.H
	}
	return nil
}

type GetHobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *GetHobbyRequest) Reset() {
	*x = GetHobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_hobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHobbyRequest) ProtoMessage() {}

func (x *GetHobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_hobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHobbyRequest.ProtoReflect.Descriptor instead.
func (*GetHobbyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_hobby_proto_rawDescGZIP(), []int{2}
}

func (x *GetHobbyRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetHobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H *Hobby `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *GetHobbyResponse) Reset() {
	*x = GetHobbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_hobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHobbyResponse) ProtoMessage() {}

func (x *GetHobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_hobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHobbyResponse.ProtoReflect.Descriptor instead.
func (*GetHobbyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_hobby_proto_rawDescGZIP(), []int{3}
}

func (x *GetHobbyResponse) GetH() *Hobby {
	if x != nil {
		return x.H
	}
	return nil
}

type UpdateHobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        int32  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Era           int32  `protobuf:"varint,2,opt,name=Era,proto3" json:"Era,omitempty"`
	City          string `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	Gender        string `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Height        int32  `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	Weight        int32  `protobuf:"varint,6,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Speaklanguage string `protobuf:"bytes,7,opt,name=Speaklanguage,proto3" json:"Speaklanguage,omitempty"`
	FindType      string `protobuf:"bytes,8,opt,name=FindType,proto3" json:"FindType,omitempty"`
	FindTarget    string `protobuf:"bytes,9,opt,name=FindTarget,proto3" json:"FindTarget,omitempty"`
	Experience    int32  `protobuf:"varint,10,opt,name=Experience,proto3" json:"Experience,omitempty"`
	Sociability   string `protobuf:"bytes,11,opt,name=Sociability,proto3" json:"Sociability,omitempty"`
	Certification bool   `protobuf:"varint,12,opt,name=Certification,proto3" json:"Certification,omitempty"`
}

func (x *UpdateHobbyRequest) Reset() {
	*x = UpdateHobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_hobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHobbyRequest) ProtoMessage() {}

func (x *UpdateHobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_hobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHobbyRequest.ProtoReflect.Descriptor instead.
func (*UpdateHobbyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_hobby_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateHobbyRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateHobbyRequest) GetEra() int32 {
	if x != nil {
		return x.Era
	}
	return 0
}

func (x *UpdateHobbyRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateHobbyRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateHobbyRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UpdateHobbyRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateHobbyRequest) GetSpeaklanguage() string {
	if x != nil {
		return x.Speaklanguage
	}
	return ""
}

func (x *UpdateHobbyRequest) GetFindType() string {
	if x != nil {
		return x.FindType
	}
	return ""
}

func (x *UpdateHobbyRequest) GetFindTarget() string {
	if x != nil {
		return x.FindTarget
	}
	return ""
}

func (x *UpdateHobbyRequest) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *UpdateHobbyRequest) GetSociability() string {
	if x != nil {
		return x.Sociability
	}
	return ""
}

func (x *UpdateHobbyRequest) GetCertification() bool {
	if x != nil {
		return x.Certification
	}
	return false
}

type UpdateHobbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H *Hobby `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *UpdateHobbyResponse) Reset() {
	*x = UpdateHobbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_hobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHobbyResponse) ProtoMessage() {}

func (x *UpdateHobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_hobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHobbyResponse.ProtoReflect.Descriptor instead.
func (*UpdateHobbyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_hobby_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateHobbyResponse) GetH() *Hobby {
	if x != nil {
		return x.H
	}
	return nil
}

var File_rpc_hobby_proto protoreflect.FileDescriptor

var file_rpc_hobby_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xe4, 0x02, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x62,
	0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x45, 0x72, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x24, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x13, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x01, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x01, 0x68, 0x22, 0x29, 0x0a, 0x0f, 0x67, 0x65, 0x74,
	0x48, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x48, 0x6f, 0x62, 0x62, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x01, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x68, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x01,
	0x68, 0x22, 0xe4, 0x02, 0x0a, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x62, 0x62,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45,
	0x72, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x24,
	0x0a, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x43, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x13, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x48, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x17, 0x0a, 0x01, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x68, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x01, 0x68, 0x42, 0x0c, 0x5a, 0x0a, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_hobby_proto_rawDescOnce sync.Once
	file_rpc_hobby_proto_rawDescData = file_rpc_hobby_proto_rawDesc
)

func file_rpc_hobby_proto_rawDescGZIP() []byte {
	file_rpc_hobby_proto_rawDescOnce.Do(func() {
		file_rpc_hobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_hobby_proto_rawDescData)
	})
	return file_rpc_hobby_proto_rawDescData
}

var file_rpc_hobby_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_hobby_proto_goTypes = []interface{}{
	(*CreateHobbyRequest)(nil),  // 0: pb.createHobbyRequest
	(*CreateHobbyResponse)(nil), // 1: pb.createHobbyResponse
	(*GetHobbyRequest)(nil),     // 2: pb.getHobbyRequest
	(*GetHobbyResponse)(nil),    // 3: pb.getHobbyResponse
	(*UpdateHobbyRequest)(nil),  // 4: pb.updateHobbyRequest
	(*UpdateHobbyResponse)(nil), // 5: pb.updateHobbyResponse
	(*Hobby)(nil),               // 6: pb.hobby
}
var file_rpc_hobby_proto_depIdxs = []int32{
	6, // 0: pb.createHobbyResponse.h:type_name -> pb.hobby
	6, // 1: pb.getHobbyResponse.h:type_name -> pb.hobby
	6, // 2: pb.updateHobbyResponse.h:type_name -> pb.hobby
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_hobby_proto_init() }
func file_rpc_hobby_proto_init() {
	if File_rpc_hobby_proto != nil {
		return
	}
	file_hobby_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_hobby_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_hobby_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHobbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_hobby_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_hobby_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHobbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_hobby_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_hobby_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHobbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_hobby_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_hobby_proto_goTypes,
		DependencyIndexes: file_rpc_hobby_proto_depIdxs,
		MessageInfos:      file_rpc_hobby_proto_msgTypes,
	}.Build()
	File_rpc_hobby_proto = out.File
	file_rpc_hobby_proto_rawDesc = nil
	file_rpc_hobby_proto_goTypes = nil
	file_rpc_hobby_proto_depIdxs = nil
}
