// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: socialmedia.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocialMedia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TargetID    int32 `protobuf:"varint,2,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	Image       bool  `protobuf:"varint,3,opt,name=Image,proto3" json:"Image,omitempty"`
	Contact     bool  `protobuf:"varint,4,opt,name=Contact,proto3" json:"Contact,omitempty"`
	Location    bool  `protobuf:"varint,5,opt,name=Location,proto3" json:"Location,omitempty"`
	Appointment bool  `protobuf:"varint,6,opt,name=Appointment,proto3" json:"Appointment,omitempty"`
	Sns         bool  `protobuf:"varint,7,opt,name=Sns,proto3" json:"Sns,omitempty"`
}

func (x *SocialMedia) Reset() {
	*x = SocialMedia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socialmedia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMedia) ProtoMessage() {}

func (x *SocialMedia) ProtoReflect() protoreflect.Message {
	mi := &file_socialmedia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMedia.ProtoReflect.Descriptor instead.
func (*SocialMedia) Descriptor() ([]byte, []int) {
	return file_socialmedia_proto_rawDescGZIP(), []int{0}
}

func (x *SocialMedia) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SocialMedia) GetTargetID() int32 {
	if x != nil {
		return x.TargetID
	}
	return 0
}

func (x *SocialMedia) GetImage() bool {
	if x != nil {
		return x.Image
	}
	return false
}

func (x *SocialMedia) GetContact() bool {
	if x != nil {
		return x.Contact
	}
	return false
}

func (x *SocialMedia) GetLocation() bool {
	if x != nil {
		return x.Location
	}
	return false
}

func (x *SocialMedia) GetAppointment() bool {
	if x != nil {
		return x.Appointment
	}
	return false
}

func (x *SocialMedia) GetSns() bool {
	if x != nil {
		return x.Sns
	}
	return false
}

var File_socialmedia_proto protoreflect.FileDescriptor

var file_socialmedia_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xc1, 0x01, 0x0a, 0x0b, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x6e, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x53, 0x6e, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_socialmedia_proto_rawDescOnce sync.Once
	file_socialmedia_proto_rawDescData = file_socialmedia_proto_rawDesc
)

func file_socialmedia_proto_rawDescGZIP() []byte {
	file_socialmedia_proto_rawDescOnce.Do(func() {
		file_socialmedia_proto_rawDescData = protoimpl.X.CompressGZIP(file_socialmedia_proto_rawDescData)
	})
	return file_socialmedia_proto_rawDescData
}

var file_socialmedia_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_socialmedia_proto_goTypes = []interface{}{
	(*SocialMedia)(nil), // 0: pb.SocialMedia
}
var file_socialmedia_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_socialmedia_proto_init() }
func file_socialmedia_proto_init() {
	if File_socialmedia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_socialmedia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialMedia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_socialmedia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_socialmedia_proto_goTypes,
		DependencyIndexes: file_socialmedia_proto_depIdxs,
		MessageInfos:      file_socialmedia_proto_msgTypes,
	}.Build()
	File_socialmedia_proto = out.File
	file_socialmedia_proto_rawDesc = nil
	file_socialmedia_proto_goTypes = nil
	file_socialmedia_proto_depIdxs = nil
}
