// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: complaint.sql

package db

import (
	"context"
)

const allComplaintList = `-- name: AllComplaintList :many
SELECT user_id, cp_target_id, cp_tpye, cp_message, status, complaint_time FROM complaint
ORDER BY user_id
`

func (q *Queries) AllComplaintList(ctx context.Context) ([]Complaint, error) {
	rows, err := q.db.Query(ctx, allComplaintList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Complaint{}
	for rows.Next() {
		var i Complaint
		if err := rows.Scan(
			&i.UserID,
			&i.CpTargetID,
			&i.CpTpye,
			&i.CpMessage,
			&i.Status,
			&i.ComplaintTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createComplaint = `-- name: CreateComplaint :one
INSERT INTO complaint (
    user_id,
    cp_target_id,
    cp_tpye,
    cp_message,
    status
) VALUES (
    $1,$2,$3,$4,$5
) RETURNING user_id, cp_target_id, cp_tpye, cp_message, status, complaint_time
`

type CreateComplaintParams struct {
	UserID     int32  `json:"user_id"`
	CpTargetID int32  `json:"cp_target_id"`
	CpTpye     string `json:"cp_tpye"`
	CpMessage  string `json:"cp_message"`
	Status     string `json:"status"`
}

func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error) {
	row := q.db.QueryRow(ctx, createComplaint,
		arg.UserID,
		arg.CpTargetID,
		arg.CpTpye,
		arg.CpMessage,
		arg.Status,
	)
	var i Complaint
	err := row.Scan(
		&i.UserID,
		&i.CpTargetID,
		&i.CpTpye,
		&i.CpMessage,
		&i.Status,
		&i.ComplaintTime,
	)
	return i, err
}

const deleteComplaint = `-- name: DeleteComplaint :exec
DELETE FROM complaint
WHERE user_id = $1
`

func (q *Queries) DeleteComplaint(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteComplaint, userID)
	return err
}

const getUserComplaintList = `-- name: GetUserComplaintList :one
SELECT user_id, cp_target_id, cp_tpye, cp_message, status, complaint_time FROM complaint
WHERE user_id = $1
`

func (q *Queries) GetUserComplaintList(ctx context.Context, userID int32) (Complaint, error) {
	row := q.db.QueryRow(ctx, getUserComplaintList, userID)
	var i Complaint
	err := row.Scan(
		&i.UserID,
		&i.CpTargetID,
		&i.CpTpye,
		&i.CpMessage,
		&i.Status,
		&i.ComplaintTime,
	)
	return i, err
}
