// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: image.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO image (
    user_id,
    qr,
    icon
) VALUES (
    $1,$2,$3
) RETURNING user_id, qr, icon
`

type CreateImageParams struct {
	UserID int32  `json:"user_id"`
	Qr     string `json:"qr"`
	Icon   string `json:"icon"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage, arg.UserID, arg.Qr, arg.Icon)
	var i Image
	err := row.Scan(&i.UserID, &i.Qr, &i.Icon)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM image 
WHERE user_id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteImage, userID)
	return err
}

const getUserimageData = `-- name: GetUserimageData :one
SELECT user_id, qr, icon FROM image
WHERE user_id = $1
`

func (q *Queries) GetUserimageData(ctx context.Context, userID int32) (Image, error) {
	row := q.db.QueryRow(ctx, getUserimageData, userID)
	var i Image
	err := row.Scan(&i.UserID, &i.Qr, &i.Icon)
	return i, err
}

const listimagesList = `-- name: ListimagesList :many
SELECT user_id, qr, icon FROM image
ORDER BY user_id
`

func (q *Queries) ListimagesList(ctx context.Context) ([]Image, error) {
	rows, err := q.db.Query(ctx, listimagesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(&i.UserID, &i.Qr, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE image
SET icon = $2
WHERE user_id = $1
RETURNING user_id, qr, icon
`

type UpdateImageParams struct {
	UserID int32  `json:"user_id"`
	Icon   string `json:"icon"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage, arg.UserID, arg.Icon)
	var i Image
	err := row.Scan(&i.UserID, &i.Qr, &i.Icon)
	return i, err
}
