// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accompanyrequest struct {
	UserID        int32              `json:"user_id"`
	Era           int32              `json:"era"`
	Country       string             `json:"country"`
	City          string             `json:"city"`
	Gender        string             `json:"gender"`
	FindType      string             `json:"find_type"`
	FindTarget    string             `json:"find_target"`
	Sociability   string             `json:"sociability"`
	Certification pgtype.Bool        `json:"certification"`
	InfoChangedAt pgtype.Timestamptz `json:"info_changed_at"`
}

type Canchangeinformation struct {
	UserID        int32              `json:"user_id"`
	Nickname      string             `json:"nickname"`
	City          string             `json:"city"`
	Sexual        string             `json:"sexual"`
	Height        int32              `json:"height"`
	Weight        int32              `json:"weight"`
	Education     string             `json:"education"`
	Job           string             `json:"job"`
	AnnualSalary  int32              `json:"annual_salary"`
	Sociability   string             `json:"sociability"`
	Religious     string             `json:"religious"`
	Introduce     string             `json:"introduce"`
	InfoChangedAt pgtype.Timestamptz `json:"info_changed_at"`
}

type Changetargetuser struct {
	UserID       int32              `json:"user_id"`
	ChangeUserID int32              `json:"change_user_id"`
	Reason       string             `json:"reason"`
	ReplyUserID  int32              `json:"reply_user_id"`
	ChangeTime   pgtype.Timestamptz `json:"change_time"`
}

type Complaint struct {
	UserID        int32              `json:"user_id"`
	CpTargetID    int32              `json:"cp_target_id"`
	CpTpye        string             `json:"cp_tpye"`
	CpMessage     string             `json:"cp_message"`
	Status        string             `json:"status"`
	ComplaintTime pgtype.Timestamptz `json:"complaint_time"`
}

type Fixinformation struct {
	UserID            int32              `json:"user_id"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Email             string             `json:"email"`
	HashedPassword    string             `json:"hashed_password"`
	Birth             pgtype.Date        `json:"birth"`
	Country           string             `json:"country"`
	Gender            string             `json:"gender"`
	Blood             string             `json:"blood"`
	Age               int32              `json:"age"`
	Constellation     string             `json:"constellation"`
	Certification     pgtype.Bool        `json:"certification"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
}

type Hobbyrequest struct {
	UserID        int32              `json:"user_id"`
	Era           int32              `json:"era"`
	Country       string             `json:"country"`
	City          string             `json:"city"`
	Gender        string             `json:"gender"`
	Height        int32              `json:"height"`
	Weight        int32              `json:"weight"`
	FindType      string             `json:"find_type"`
	FindTarget    string             `json:"find_target"`
	Experience    int32              `json:"experience"`
	Sociability   string             `json:"sociability"`
	Certification pgtype.Bool        `json:"certification"`
	InfoChangedAt pgtype.Timestamptz `json:"info_changed_at"`
}

type Image struct {
	UserID int32  `json:"user_id"`
	Qr     string `json:"qr"`
	Icon   string `json:"icon"`
}

type Loverrequest struct {
	UserID        int32              `json:"user_id"`
	MinAge        int32              `json:"min_age"`
	MaxAge        int32              `json:"max_age"`
	Country       string             `json:"country"`
	City          string             `json:"city"`
	Age           int32              `json:"age"`
	Gender        string             `json:"gender"`
	Constellation string             `json:"constellation"`
	Blood         string             `json:"blood"`
	Sexual        string             `json:"sexual"`
	Height        int32              `json:"height"`
	Weight        int32              `json:"weight"`
	Education     string             `json:"education"`
	Job           string             `json:"job"`
	AnnualSalary  int32              `json:"annual_salary"`
	Sociability   string             `json:"sociability"`
	Religious     string             `json:"religious"`
	Certification pgtype.Bool        `json:"certification"`
	InfoChangedAt pgtype.Timestamptz `json:"info_changed_at"`
}

type Targetlist struct {
	UserID    int32              `json:"user_id"`
	Target1ID pgtype.Int4        `json:"target_1_id"`
	Target2ID pgtype.Int4        `json:"target_2_id"`
	Target3ID pgtype.Int4        `json:"target_3_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
