// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import "time"

type Record struct {
	TargetID  int32              `json:"target_id"`
	MsgType   string             `json:"msg_type"`
	Message   string        `json:"message"`
	Images    string        `json:"images"`
	CreatedAt time.Time `json:"created_at"`
}
