// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Recordtest struct {
	UserID    int32              `json:"user_id"`
	TargetID  int32              `json:"target_id"`
	Message   pgtype.Text        `json:"message"`
	Images    pgtype.Text        `json:"images"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
