// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type ChatQuerier interface {
	Getrecord(ctx context.Context, userID int32) (Recordtest, error)
	Listrecord(ctx context.Context) ([]Recordtest, error)
	recordTest(ctx context.Context, arg recordTestParams) (Recordtest, error)
}

var _ ChatQuerier = (*Queries)(nil)
