// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type ChatQuerier interface {
	CreateChatTable(ctx context.Context, tablename string) error
	CreateRecord(ctx context.Context, arg CreateRecordParams, tablename string) (Record, error)
	DeleteRecord(ctx context.Context, arg DeleteRecordParams, tablename string) error
	GetRecord(ctx context.Context, targetID int32, tablename string) ([]Record, error)
	UpdateRecord(ctx context.Context, arg UpdateRecordParams, tablename string) (Record, error)
}

var _ChatQuerier = (*Queries)(nil)
