


// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
    "context"
)


type ChatQuerier interface {
    CreateChatTable(ctx context.Context, tablename string) error
    CreateRecord(ctx context.Context, arg CreateRecordParams, tablename string) (Record, error)
    DeleteRecord(ctx context.Context, arg DeleteRecordParams, tablename string) error
    GetLastMsg(ctx context.Context, targetID int32, tablename string) (GetLastMsgRow, error) 
    GetRecord(ctx context.Context, targetID int32, tablename string) ([]Record, error)
    GetTargetID(ctx context.Context,tablename string) ([]int32, error)
    UpdateRecord(ctx context.Context, arg UpdateRecordParams, tablename string) (Record, error)
}


var _ ChatQuerier = (*Queries)(nil)