CREATE TABLE "fixinformation" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR NOT NULL,
  "email" VARCHAR UNIQUE NOT NULL,
  "hashed_password" VARCHAR NOT NULL,
  "birth" VARCHAR NOT NULL,
  "country" VARCHAR NOT NULL,
  "gender" VARCHAR NOT NULL,
  "blood" VARCHAR NOT NULL,
  "age" INT NOT NULL,
  "constellation" VARCHAR NOT NULL,
  "certification" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW()),
  "password_changed_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW())
);

CREATE TABLE "canchangeinformation" (
  "user_id" INT PRIMARY KEY,
  "nickname" VARCHAR NOT NULL,
  "city" VARCHAR NOT NULL,
  "sexual" VARCHAR NOT NULL,
  "height" INT NOT NULL,
  "weight" INT NOT NULL,
  "speaklanguage" VARCHAR NOT NULL,
  "education" VARCHAR NOT NULL,
  "job" VARCHAR NOT NULL,
  "annual_salary" INT NOT NULL,
  "sociability" VARCHAR NOT NULL,
  "religious" VARCHAR NOT NULL,
  "introduce" VARCHAR NOT NULL,
  "info_changed_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW())
);

CREATE TABLE "loverrequest" (
  "user_id" INT PRIMARY KEY,
  "min_age" INT NOT NULL,
  "max_age" INT NOT NULL,
  "city" VARCHAR NOT NULL,
  "gender" VARCHAR NOT NULL,
  "constellation" VARCHAR NOT NULL,
  "sexual" VARCHAR NOT NULL,
  "height" INT NOT NULL,
  "weight" INT NOT NULL,
  "speaklanguage" VARCHAR NOT NULL,
  "job" VARCHAR NOT NULL,
  "annual_salary" INT NOT NULL,
  "sociability" VARCHAR NOT NULL,
  "religious" VARCHAR NOT NULL,
  "certification" BOOLEAN DEFAULT FALSE,
  "info_changed_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW())
);

CREATE TABLE "hobbyrequest" (
  "user_id" INT PRIMARY KEY,
  "era" INT,
  "city" VARCHAR NOT NULL,
  "gender" VARCHAR NOT NULL,
  "height" INT,
  "weight" INT,
  "speaklanguage" VARCHAR NOT NULL,
  "find_type" VARCHAR NOT NULL,
  "find_target" VARCHAR NOT NULL,
  "experience" INT,
  "sociability" VARCHAR,
  "certification" BOOLEAN DEFAULT FALSE,
  "info_changed_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW())
);

CREATE TABLE "accompanyrequest" (
  "user_id" INT PRIMARY KEY,
  "era" INT,
  "city" VARCHAR NOT NULL,
  "gender" VARCHAR,
  "speaklanguage" VARCHAR NOT NULL,
  "find_type" VARCHAR NOT NULL,
  "find_target" VARCHAR NOT NULL,
  "sociability" VARCHAR NOT NULL,
  "certification" BOOLEAN DEFAULT FALSE,
  "info_changed_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW())
);

CREATE TABLE "image" (
  "user_id" INT PRIMARY KEY,
  "qr" VARCHAR UNIQUE NOT NULL,
  "img1" VARCHAR NOT NULL,
  "img2" VARCHAR,
  "img3" VARCHAR,
  "img4" VARCHAR,
  "img5" VARCHAR
);

CREATE TABLE "targetlist" (
  "user_id" INT PRIMARY KEY,
  "target_1_id" INT NOT NULL,
  "target_2_id" INT,
  "target_3_id" INT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW())
);

CREATE TABLE "changetargetuser" (
  "user_id" INT PRIMARY KEY,
  "change_user_id" INT NOT NULL,
  "reason" VARCHAR NOT NULL,
  "reply_user_id" INT NOT NULL,
  "frequency" INT NOT NULL DEFAULT (0),
  "change_time" TIMESTAMPTZ NOT NULL DEFAULT (NOW())
);

CREATE TABLE "complaint" (
  "cp_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "user_id" INT NOT NULL,
  "cp_target_id" INT NOT NULL,
  "cp_type" VARCHAR NOT NULL,
  "cp_message" VARCHAR NOT NULL,
  "status" VARCHAR DEFAULT 'active',
  "complaint_time" TIMESTAMPTZ NOT NULL DEFAULT (NOW())
);

ALTER TABLE "canchangeinformation" ADD FOREIGN KEY ("user_id") REFERENCES "fixinformation" ("user_id");

ALTER TABLE "loverrequest" ADD FOREIGN KEY ("user_id") REFERENCES "fixinformation" ("user_id");

ALTER TABLE "hobbyrequest" ADD FOREIGN KEY ("user_id") REFERENCES "fixinformation" ("user_id");

ALTER TABLE "accompanyrequest" ADD FOREIGN KEY ("user_id") REFERENCES "fixinformation" ("user_id");

ALTER TABLE "image" ADD FOREIGN KEY ("user_id") REFERENCES "fixinformation" ("user_id");

ALTER TABLE "targetlist" ADD FOREIGN KEY ("user_id") REFERENCES "fixinformation" ("user_id");

ALTER TABLE "changetargetuser" ADD FOREIGN KEY ("user_id") REFERENCES "fixinformation" ("user_id");

ALTER TABLE "complaint" ADD FOREIGN KEY ("user_id") REFERENCES "fixinformation" ("user_id");