// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: targetlist.sql

package db

import (
	"context"
)

const allTargetUserList = `-- name: AllTargetUserList :many
SELECT user_id, target_1_id, target_2_id, target_3_id, updated_at FROM targetlist
ORDER BY user_id
`

func (q *Queries) AllTargetUserList(ctx context.Context) ([]Targetlist, error) {
	rows, err := q.db.Query(ctx, allTargetUserList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Targetlist{}
	for rows.Next() {
		var i Targetlist
		if err := rows.Scan(
			&i.UserID,
			&i.Target1ID,
			&i.Target2ID,
			&i.Target3ID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTargetList = `-- name: DeleteTargetList :exec
DELETE FROM targetlist 
WHERE user_id = $1
`

func (q *Queries) DeleteTargetList(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteTargetList, userID)
	return err
}

const getTargetUserList = `-- name: GetTargetUserList :one
SELECT user_id, target_1_id, target_2_id, target_3_id, updated_at FROM targetlist
WHERE user_id = $1
`

func (q *Queries) GetTargetUserList(ctx context.Context, userID int32) (Targetlist, error) {
	row := q.db.QueryRow(ctx, getTargetUserList, userID)
	var i Targetlist
	err := row.Scan(
		&i.UserID,
		&i.Target1ID,
		&i.Target2ID,
		&i.Target3ID,
		&i.UpdatedAt,
	)
	return i, err
}

const targetUserList = `-- name: TargetUserList :one
INSERT INTO targetlist (
    user_id,
    target_1_id,
    target_2_id,
    target_3_id
) VALUES (
    $1,$2,$3,$4
) RETURNING user_id, target_1_id, target_2_id, target_3_id, updated_at
`

type TargetUserListParams struct {
	UserID    int32       `json:"user_id"`
	Target1ID int32       `json:"target_1_id"`
	Target2ID int32 `json:"target_2_id"`
	Target3ID int32 `json:"target_3_id"`
}

func (q *Queries) TargetUserList(ctx context.Context, arg TargetUserListParams) (Targetlist, error) {
	row := q.db.QueryRow(ctx, targetUserList,
		arg.UserID,
		arg.Target1ID,
		arg.Target2ID,
		arg.Target3ID,
	)
	var i Targetlist
	err := row.Scan(
		&i.UserID,
		&i.Target1ID,
		&i.Target2ID,
		&i.Target3ID,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTargetList = `-- name: UpdateTargetList :one
UPDATE targetlist
SET target_1_id = $2,
    target_2_id = $3,
    target_3_id = $4
WHERE user_id = $1 
RETURNING user_id, target_1_id, target_2_id, target_3_id, updated_at
`

type UpdateTargetListParams struct {
	UserID    int32       `json:"user_id"`
	Target1ID int32       `json:"target_1_id"`
	Target2ID int32 `json:"target_2_id"`
	Target3ID int32 `json:"target_3_id"`
}

func (q *Queries) UpdateTargetList(ctx context.Context, arg UpdateTargetListParams) (Targetlist, error) {
	row := q.db.QueryRow(ctx, updateTargetList,
		arg.UserID,
		arg.Target1ID,
		arg.Target2ID,
		arg.Target3ID,
	)
	var i Targetlist
	err := row.Scan(
		&i.UserID,
		&i.Target1ID,
		&i.Target2ID,
		&i.Target3ID,
		&i.UpdatedAt,
	)
	return i, err
}
